name: dino
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0.221
  - numpy=1.19.2
  - pillow=8.3.1
  - pip=21.2.2
  - python=3.6.13
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pip:
      - pydevd-pycharm==223.8836.43
      - submitit==1.4.5
      - timm==0.3.4
